/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const OTP_VERIFY = "OTP_VERIFY";
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const STOP_NOTIFICATIONS = "STOP_NOTIFICATIONS";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";


/* Orders */
export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_FROM_CHANNEL = "GET_ORDERS_FROM_CHANNEL";
export const STOP_ORDERS_FROM_CHANNEL = "STOP_ORDERS_FROM_CHANNEL";
export const ORDER_INCOMING_FROM_CHANNEL = "ORDER_INCOMING_FROM_CHANNEL";
export const GET_ORDERS_INCOMING_SUCCESS = "GET_ORDERS_INCOMING_SUCCESS";
export const GET_ORDERS_HISTORY_SUCCESS = "GET_ORDERS_HISTORY_SUCCESS";
export const GET_ORDERS_ACTIVE_SUCCESS = "GET_ORDERS_ACTIVE_SUCCESS";
export const EDIT_ORDER_STATUS = "EDIT_ORDER_STATUS";
export const EDIT_ORDER_STATUS_SUCCESS = "EDIT_ORDER_STATUS_SUCCESS";
export const DELETE_ORDER = "DELETE_ORDER";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ACCEPT_ORDER_SUCCESS = "DELETE_ACCEPT_ORDER_SUCCESS";
export const DELETE_PICKEDUP_ORDER_SUCCESS = "DELETE_PICKEDUP_ORDER_SUCCESS";
export const ORDER_FAILURE = "ORDER_FAILURE";

/* Wizard */
export const IMAGE_UPLOAD = "IMAGE_UPLOAD";
export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS";
export const EDIT_PINFO = "EDIT_PINFO";
export const ADD_INFO_SUCCESS = "ADD_INFO_SUCCESS";
export const ADD_RESTAURANT = "ADD_RESTAURANT";
export const ADD_RESTAURANT_SUCCESS = "ADD_RESTAURANT_SUCCESS";
export const ADD_RESTAURANT_FAILURE = "ADD_RESTAURANT_FAILURE";
export const ADD_ACCESS_INFO="ADD_ACCESS_INFO";
export const ADD_ACCESS_INFO_SUCCESS="ADD_ACCESS_INFO_SUCCESS";
export const WIZARD_FAILURE = "WIZARD_FAILURE";

/* Dishes Menu */
export const GET_ALL_RESTAURANTS = "GET_ALL_RESTAURANTS";
export const GET_ALL_RESTAURANTS_SUCCESS = "GET_ALL_RESTAURANTS_SUCCESS";
export const EDIT_RESTAURANT = "EDIT_RESTAURANT";
export const EDIT_RESTAURANT_SUCCESS = "EDIT_RESTAURANT_SUCCESS";
export const GET_BRANCHES = "GET_BRANCHES";
export const GET_BRANCHES_SUCCESS = "GET_BRANCHES_SUCCESS";
export const ADD_BRANCH = "ADD_BRANCH";
export const ADD_BRANCH_SUCCESS = "ADD_BRANCH_SUCCESS";
export const EDIT_BRANCH = "EDIT_BRANCH";
export const EDIT_BRANCH_SUCCESS = "EDIT_BRANCH_SUCCESS";
export const DELETE_BRANCH = "DELETE_BRANCH";
export const DELETE_BRANCH_SUCCESS = "DELETE_BRANCH_SUCCESS";
export const GET_DISHES = "GET_DISHES";
export const GET_DISHES_SUCCESS = "GET_DISHES_SUCCESS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const ADD_DISH = "ADD_DISH";
export const ADD_DISH_SUCCESS = "ADD_DISH_SUCCESS";
export const EDIT_DISH = "EDIT_DISH";
export const EDIT_DISH_SUCCESS = "EDIT_DISH_SUCCESS";
export const DELETE_DISH = "DELETE_DISH";
export const DELETE_DISH_SUCCESS = "DELETE_DISH_SUCCESS";
export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const ADD_CATEGORIES_SUCCESS = "ADD_CATEGORIES_SUCCESS";
export const EDIT_CATEGORIES = "EDIT_CATEGORIES";
export const EDIT_CATEGORIES_SUCCESS = "EDIT_CATEGORIES_SUCCESS";
export const DELETE_CATEGORIES = "DELETE_CATEGORIES";
export const DELETE_CATEGORIES_SUCCESS = "DELETE_CATEGORIES_SUCCESS";
export const GET_SAMPLE_CATEGORIES = "GET_SAMPLE_CATEGORIES";
export const GET_SAMPLE_CATEGORIES_SUCCESS = "GET_SAMPLE_CATEGORIES_SUCCESS";
export const MIGRATE_MENU = "MIGRATE_MENU";
export const MIGRATE_MENU_SUCCESS = "MIGRATE_MENU_SUCCESS";
export const MENU_FAILURE = "MENU_FAILURE";

/* Manage */

export const ADD_WAITER = "ADD_WAITER";
export const ADD_WAITER_SUCCESS = "ADD_WAITER_SUCCESS";
export const EDIT_WAITER = "EDIT_WAITER";
export const EDIT_WAITER_SUCCESS = "EDIT_WAITER_SUCCESS";
export const DELETE_WAITER = "DELETE_WAITER";
export const DELETE_WAITER_SUCCESS = "DELETE_WAITER_SUCCESS";
export const GET_ALL_WAITERS = "GET_ALL_WAITERS";
export const GET_ALL_WAITERS_SUCCESS = "GET_ALL_WAITERS_SUCCESS";

export const ADD_MANAGER = "ADD_MANAGER";
export const ADD_MANAGER_SUCCESS = "ADD_MANAGER_SUCCESS";
export const EDIT_MANAGER = "EDIT_MANAGER";
export const EDIT_MANAGER_SUCCESS = "EDIT_MANAGER_SUCCESS";
export const DELETE_MANAGER = "DELETE_MANAGER";
export const DELETE_MANAGER_SUCCESS = "DELETE_MANAGER_SUCCESS";
export const GET_MANAGER = "GET_MANAGER";
export const GET_MANAGER_SUCCESS = "GET_MANAGER_SUCCESS";
export const GET_FEEDBACK_FIELDS = "GET_FEEDBACK_FIELDS";
export const GET_FEEDBACK_FIELDS_SUCCESS = "GET_FEEDBACK_FIELDS_SUCCESS";
export const ADD_FEEDBACK_FIELDS = "ADD_FEEDBACK_FIELDS";
export const ADD_FEEDBACK_FIELDS_SUCCESS = "ADD_FEEDBACK_FIELDS_SUCCESS";
export const MANAGE_FAILURE = "MANAGE_FAILURE";
/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS = "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* Inventory */
export const GET_INVENTORY = "GET_INVENTORY";
export const GET_INVENTORY_SUCCESS = "GET_INVENTORY_SUCCESS";
export const ADD_INVENTORY = "ADD_INVENTORY";
export const ADD_INVENTORY_SUCCESS = "ADD_INVENTORY_SUCCESS";
export const EDIT_INVENTORY = "EDIT_INVENTORY";
export const EDIT_INVENTORY_SUCCESS = "EDIT_INVENTORY_SUCCESS";
export const DELETE_INVENTORY = "DELETE_INVENTORY";
export const CALCULATE_INVENTORY = "CALCULATE_INVENTORY";
export const CALCULATE_INVENTORY_SUCCESS = "CALCULATE_INVENTORY_SUCCESS";
export const DELETE_INVENTORY_SUCCESS = "DELETE_INVENTORY_SUCCESS";
export const INVENTORY_FAILURE = "INVENTORY_FAILURE";

/* Dashboard */
export const GET_SUMMARY = "GET_SUMMARY";
export const GET_SUMMARY_SUCCESS = "GET_SUMMARY_SUCCESS";
export const GET_TOP_SOLD_DISHES = "GET_TOP_SOLD_DISHES";
export const GET_TOP_SOLD_DISHES_SUCCESS = "GET_TOP_SOLD_DISHES_SUCCESS";
export const GET_LEAST_SOLD_DISHES = "GET_LEAST_SOLD_DISHES";
export const GET_LEAST_SOLD_DISHES_SUCCESS = "GET_LEAST_SOLD_DISHES_SUCCESS";
export const GET_FEEDBACK_COMMENTS = "GET_FEEDBACK_COMMENTS";
export const GET_SALES="GET_SALES";
export const GET_SALES_SUCCESS="GET_SALES_SUCCESS";
export const GET_SALES_TREND="GET_SALES_TREND";
export const GET_SALES_TREND_SUCCESS="GET_SALES_TREND_SUCCESS";
export const GET_SALES_WEEKLY="GET_SALES_WEEKLY";
export const GET_SALES_WEEKLY_SUCCESS="GET_SALES_WEEKLY_SUCCESS";
export const GET_SALES_YEARLY="GET_SALES_YEARLY";
export const GET_SALES_YEARLY_SUCCESS="GET_SALES_YEARLY_SUCCESS";
export const GET_FEEDBACK_COMMENTS_SUCCESS = "GET_FEEDBACK_COMMENTS_SUCCESS";
export const GET_ITEM_SALES_STATS="GET_ITEM_SALES_STATS";
export const GET_ITEM_SALES_STATS_SUCCESS="GET_ITEM_SALES_STATS_SUCCESS";
export const GET_CATEGORY_SALES_STATS="GET_CATEGORY_SALES_STATS";
export const GET_CATEGORY_SALES_STATS_SUCCESS="GET_CATERGORY_SALES_STATS_SUCCESS";
export const GET_ITEM_SALES_STATS_HOURLY="GET_ITEM_SALES_STATS_HOURLY";
export const GET_ITEM_SALES_STATS_HOURLY_SUCCESS="GET_ITEM_SALES_STATS_HOURLY_SUCCESS";
export const GET_CATEGORY_SALES_STATS_HOURLY="GET_CATEGORY_SALES_STATS_HOURLY";
export const GET_CATEGORY_SALES_STATS_HOURLY_SUCCESS="GET_CATEGORY_SALES_STATS_HOURLY_SUCCESS";
export const GET_PAYMENT_METHODS="GET_PAYMENT_METHODS"
export const GET_PAYMENT_METHODS_SUCCESS="GET_PAYMENT_METHODS_SUCCESS"
export const DASHBOARD_FAILURE = "DASHBOARD_FAILURE";


/* Services */
export const ADD_SERVICES="ADD_SERVICES"
export const ADD_SERVICES_SUCCESS="ADD_SERVICES_SUCCESS";
export const GET_SERVICES="GET_SERVICES";
export const GET_SERVICES_SUCCESS="GET_SERVICES_SUCCESS";
export const UPDATE_SERVICES="UPDATE_SERVICES"
export const UPDATE_SERVICES_SUCCESS="UPDATE_SERVICES_SUCCESS";
export const SERVICE_FALIURE="SERVICE_FALIURE"


export * from "./dishesMenu/actions";
export * from "./menu/actions";
export * from "./settings/actions";
export * from "./auth/actions";
export * from "./wizard/actions";
export * from "./dashboard/actions";
export * from "./manage/actions";
export * from "./orders/actions";
export * from "./inventory/actions";
export * from "./services/actions";